package graphics.assets.surface

import org.lwjgl.opengl.GL40.GL_VERTEX_SHADER
import org.lwjgl.opengl.GL40.GL_TESS_CONTROL_SHADER
import org.lwjgl.opengl.GL40.GL_TESS_EVALUATION_SHADER
import org.lwjgl.opengl.GL40.GL_GEOMETRY_SHADER
import org.lwjgl.opengl.GL40.GL_FRAGMENT_SHADER
import org.lwjgl.opengl.GL43.GL_COMPUTE_SHADER

enum class ShaderType(val value: Int) {
    VERTEX_SHADER (GL_VERTEX_SHADER),
    TESSELLATION_CONTROL_SHADER (GL_TESS_CONTROL_SHADER),
    TESSELLATION_EVALUATION_SHADER (GL_TESS_EVALUATION_SHADER),
    GEOMETRY_SHADER (GL_GEOMETRY_SHADER),
    FRAGMENT_SHADER (GL_FRAGMENT_SHADER),
    COMPUTE_SHADER (GL_COMPUTE_SHADER)
}